# Generated by Django 5.2.1 on 2025-05-08 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='image',
            field=models.ImageField(upload_to='webapp/static/pic/type'),
        ),
        migrations.AlterField(
            model_name='viewproduct',
            name='product',
            field=models.ImageField(upload_to='webapp/static/pic/product'),
        ),
    ]
