# Generated by Django 5.2.1 on 2025-05-09 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0004_cart_cartitem_infoproduct_order_orderconfirmation_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewproduct',
            name='slug',
        ),
    ]
