# Generated by Django 5.2.1 on 2025-05-10 01:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0005_remove_viewproduct_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeproduct',
            name='slug',
        ),
    ]
