# Generated by Django 5.2.1 on 2025-05-10 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0006_remove_typeproduct_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='image',
            field=models.ImageField(upload_to='media/type'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='media/avatar', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='viewproduct',
            name='product',
            field=models.ImageField(upload_to='media/product', verbose_name='Изображение товара'),
        ),
    ]
