# Generated by Django 5.2.1 on 2025-05-26 23:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0008_faq'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FAQ',
        ),
    ]
