# Generated by Django 5.2.1 on 2025-05-27 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0009_delete_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewproduct',
            name='product',
            field=models.ImageField(upload_to='product', verbose_name='Изображение товара'),
        ),
    ]
