# Generated by Django 5.2.1 on 2025-05-28 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0011_viewproduct_quantity_viewproduct_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewproduct',
            name='cut_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Огранка'),
        ),
    ]
