# Generated by Django 5.2.1 on 2025-05-28 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0012_viewproduct_cut_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewproduct',
            name='type_material',
            field=models.CharField(choices=[('all', 'Показать все'), ('gold', 'Золото'), ('silver', 'Серебро')], default='all', max_length=10, verbose_name='Вид материала'),
        ),
    ]
