# Generated by Django 5.2.1 on 2025-05-28 13:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0013_viewproduct_type_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='viewproduct',
            name='cut_type',
        ),
    ]
