# Generated by Django 5.2.1 on 2025-05-28 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0014_remove_viewproduct_cut_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='discount',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='old_price',
        ),
        migrations.AddField(
            model_name='viewproduct',
            name='discount',
            field=models.PositiveIntegerField(default=0, verbose_name='Скидка (%)'),
        ),
        migrations.AddField(
            model_name='viewproduct',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
