# Generated by Django 5.2.1 on 2025-05-28 19:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0015_remove_infoproduct_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='viewproduct',
            name='final_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
