# Generated by Django 5.2.1 on 2025-05-28 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0016_viewproduct_final_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='viewproduct',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Скидка (%)'),
        ),
    ]
