# Generated by Django 5.2.1 on 2025-05-28 21:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0018_alter_infoproduct_options_alter_viewproduct_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='color',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='weight',
        ),
    ]
