# Generated by Django 5.2.1 on 2025-06-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0020_alter_cart_user_alter_wishlist_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='infoproduct',
            name='second_image',
            field=models.ImageField(blank=True, null=True, upload_to='product2', verbose_name='Изображение товара2'),
        ),
    ]
