# Generated by Django 5.2.1 on 2025-06-03 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0021_infoproduct_second_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='second_image',
        ),
        migrations.AddField(
            model_name='viewproduct',
            name='product2',
            field=models.ImageField(blank=True, null=True, upload_to='product2', verbose_name='Изображение товара2'),
        ),
    ]
