# Generated by Django 5.2.1 on 2025-06-03 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0022_remove_infoproduct_second_image_viewproduct_product2'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='infoproduct',
            name='material',
        ),
        migrations.RemoveField(
            model_name='infoproduct',
            name='size',
        ),
    ]
