# Generated by Django 5.2.1 on 2025-06-07 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0024_alter_productdetail_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeproduct',
            name='image',
            field=models.ImageField(upload_to='type'),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='avatar',
            field=models.ImageField(blank=True, default=None, upload_to='avatar', verbose_name='Фото профиля'),
        ),
        migrations.AlterField(
            model_name='viewproduct',
            name='product',
            field=models.ImageField(upload_to='productimage', verbose_name='Изображение товара'),
        ),
        migrations.AlterField(
            model_name='viewproduct',
            name='product2',
            field=models.ImageField(blank=True, null=True, upload_to='productimageswiper', verbose_name='Изображение товара2'),
        ),
    ]
