# Generated by Django 5.2.1 on 2025-06-10 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0026_alter_infoproduct_view_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=450, max_digits=10, verbose_name='Стоимость доставки'),
        ),
    ]
