# Generated by Django 5.2.1 on 2025-06-16 15:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0027_alter_order_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='infoproduct',
            name='view_product',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='detailed_info', to='webapp.viewproduct', verbose_name='Товар'),
        ),
    ]
