# Generated by Django 5.2.1 on 2025-06-17 02:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0028_alter_infoproduct_view_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
    ]
