# Generated by Django 5.2.1 on 2025-06-19 18:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0030_alter_paymentcard_user'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField(verbose_name='Причина отмены')),
                ('cancelled_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отмены')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Отменил')),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cancellation', to='webapp.order')),
            ],
            options={
                'verbose_name': 'Отмена заказа',
                'verbose_name_plural': 'Отмены заказов',
            },
        ),
    ]
