# Generated by Django 5.2.1 on 2025-06-19 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0031_ordercancellation'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderCancellation',
        ),
    ]
