# Generated by Django 5.2.1 on 2025-06-22 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0032_delete_ordercancellation'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cancellation_reason',
            field=models.TextField(blank=True, null=True, verbose_name='Причина отмены'),
        ),
    ]
